
# DB 
#spring.datasource.url=jdbc:oracle:thin:@오라클ip:오라클port:접속할sid 
#spring.datasource.username=이름 
#spring.datasource.password=비밀번호
#spring.datasource.driver.class-name=oracle.jdbc.OracleDriver

server:
  port: 1235

mybatis:
  type-aliases-package: com.rest.mapper
  mapper-locations: mybatis/mapper/**/*.xml

#spring:
#  datasource:
#    url: jdbc:cubrid:192.168.0.200:30000:survey_zinna:::?charset=UTF-8
#    username: dba
#    password: admin
#    driver-class-name: core.log.jdbc.driver.CUBRIDDriver